// All user-facing copy lives here (Turkish only, by club decision). Keeping strings in one typed
// catalog means no scattered literals, consistent wording, and one place for the club to review.

export const tr = {
  app: {
    name: 'Yeni Mahalle Kürek',
    clubName: 'Kdz. Ereğli Yeni Mahalle Kürek Kulübü',
    loading: 'Yükleniyor…',
  },

  common: {
    retry: 'Tekrar dene',
    cancel: 'Vazgeç',
    close: 'Kapat',
    copy: 'Kopyala',
    copied: 'Kopyalandı',
    share: 'Paylaş',
    search: 'Ara',
    show: 'Göster',
    hide: 'Gizle',
    optional: 'isteğe bağlı',
    errorTitle: 'Bir sorun oluştu',
    errorGeneric: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
    errorNetwork: 'Bağlantı kurulamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.',
    soonTitle: 'Yakında',
    soonBody: 'Bu bölüm sonraki aşamada eklenecek.',
    forbidden: 'Bu işlem için yetkiniz yok.',
    save: 'Kaydet',
    edit: 'Düzenle',
    tabsLabel: 'Bölümler',
    offline: 'Çevrimdışısınız. Görünen bilgiler güncel olmayabilir.',
    updateAvailable: 'Yeni sürüm hazır.',
    updateAction: 'Yenile',
  },

  config: {
    title: 'Uygulama yapılandırılmamış',
    body: 'Aşağıdaki ayarlar eksik veya hatalı. docs/RUNBOOK.md dosyasındaki adımları izleyin.',
  },

  auth: {
    loginTitle: 'Giriş yap',
    loginSubtitle: 'Antrenörünüzün verdiği kullanıcı adı ve şifre ile giriş yapın.',
    username: 'Kullanıcı adı',
    password: 'Şifre',
    submit: 'Giriş yap',
    submitting: 'Giriş yapılıyor…',
    usernameRequired: 'Kullanıcı adınızı yazın.',
    passwordRequired: 'Şifrenizi yazın.',
    invalidCredentials: 'Kullanıcı adı veya şifre hatalı.',
    accountDisabled: 'Hesabınız devre dışı bırakılmış. Lütfen antrenörünüzle görüşün.',
    tooManyAttempts: 'Çok fazla deneme yaptınız. Birkaç dakika sonra tekrar deneyin.',
    noAccount: 'Hesabınız yok mu? Hesapları antrenörler oluşturur; antrenörünüzle iletişime geçin.',
    logout: 'Çıkış yap',
    blockedTitle: 'Hesabınıza erişilemiyor',
    blockedBody: 'Hesabınız devre dışı bırakılmış veya bulunamadı. Lütfen antrenörünüzle görüşün.',
    changePasswordTitle: 'Yeni şifre belirleyin',
    changePasswordForced: 'Güvenliğiniz için geçici şifrenizi değiştirmeniz gerekiyor.',
    newPassword: 'Yeni şifre',
    confirmPassword: 'Yeni şifre (tekrar)',
    passwordRules: 'En az 8 karakter; harf ve rakam içermeli.',
    passwordTooShort: 'Şifre en az 8 karakter olmalı.',
    passwordNeedsLetterAndDigit: 'Şifre hem harf hem rakam içermeli.',
    passwordMismatch: 'Şifreler eşleşmiyor.',
    passwordSame: 'Yeni şifre mevcut şifrenizle aynı olamaz.',
    passwordWeak: 'Bu şifre çok zayıf. Daha güçlü bir şifre seçin.',
    passwordChanged: 'Şifreniz değiştirildi.',
    savePassword: 'Şifreyi kaydet',
    saving: 'Kaydediliyor…',
  },

  nav: {
    home: 'Ana Sayfa',
    trainings: 'Antrenmanlar',
    stats: 'İstatistik',
    profile: 'Profil',
    dashboard: 'Panel',
    members: 'Üyeler',
    more: 'Diğer',
    mainNav: 'Ana gezinme',
  },

  roles: {
    coach: 'Antrenör',
    member: 'Üye',
  },

  home: {
    greeting: (name: string) => `Merhaba, ${name}`,
    noUpcomingTitle: 'Yaklaşan antrenman yok',
    noUpcomingBody: 'Yeni bir antrenman eklendiğinde burada göreceksiniz.',
    coachNoUpcomingBody: 'İlk antrenmanı eklemek için "Antrenman ekle" düğmesine dokunun.',
    nextTraining: 'Sıradaki antrenman',
    otherUpcoming: 'Diğer yaklaşan antrenmanlar',
    coachUpcoming: 'Yaklaşan antrenmanlar',
    seeAll: 'Tümünü gör',
    manageMembers: 'Üyeleri yönet',
  },

  members: {
    title: 'Üyeler',
    add: 'Üye ekle',
    searchPlaceholder: 'İsim veya kullanıcı adı ara',
    emptyTitle: 'Henüz üye yok',
    emptyBody: 'İlk üyeyi eklemek için "Üye ekle" düğmesine dokunun.',
    noResults: 'Aramanızla eşleşen üye yok.',
    loadError: 'Üye listesi yüklenemedi.',
    inactive: 'Devre dışı',
    neverLoggedIn: 'İlk giriş bekleniyor',
    fullName: 'Ad soyad',
    phone: 'Telefon',
    fullNameRequired: 'Ad soyad en az 2 karakter olmalı.',
    usernameHint: 'Küçük harf (a-z), rakam, nokta, tire veya alt çizgi; 3–30 karakter.',
    usernameInvalid: 'Kullanıcı adı 3–30 karakter olmalı; yalnızca a-z, 0-9, nokta, tire ve alt çizgi.',
    roleLabel: 'Rol',
    createTitle: 'Yeni üye ekle',
    create: 'Hesabı oluştur',
    creating: 'Oluşturuluyor…',
    credentialsTitle: 'Hesap hazır',
    credentialsWarning: 'Bu şifre yalnızca bir kez gösterilir. Şimdi kopyalayıp üyeye iletin; üye ilk girişte yeni şifre belirleyecek.',
    credentialsUsername: 'Kullanıcı adı',
    credentialsPassword: 'Geçici şifre',
    copyInvite: 'Davet mesajını kopyala',
    inviteMessage: (appUrl: string, username: string, password: string) =>
      `Yeni Mahalle Kürek uygulaması\nAdres: ${appUrl}\nKullanıcı adı: ${username}\nGeçici şifre: ${password}\n(İlk girişte yeni şifre belirlemeniz istenecek.)`,
    detailsTitle: 'Üye işlemleri',
    resetPassword: 'Şifreyi sıfırla',
    resetConfirm: 'Yeni bir geçici şifre oluşturulsun mu? Eski şifre geçersiz olur.',
    resetDone: 'Şifre sıfırlandı',
    deactivate: 'Hesabı devre dışı bırak',
    deactivateConfirm: 'Bu kişi artık giriş yapamayacak. Geçmiş kayıtları korunur. Devam edilsin mi?',
    activate: 'Hesabı yeniden etkinleştir',
    confirmAction: 'Evet, devam et',
    activated: 'Hesap etkinleştirildi.',
    deactivated: 'Hesap devre dışı bırakıldı.',
    you: 'Siz',
  },

  push: {
    title: 'Bildirimler',
    unsupportedBrowser: 'Bu tarayıcı bildirimleri desteklemiyor.',
    iosNeedsInstall:
      'iPhone\'da bildirim almak için önce uygulamayı ana ekrana eklemeniz gerekir (aşağıdaki adımlara bakın).',
    denied: 'Bildirimler engellenmiş. Telefonunuzun ayarlarından bu uygulama için bildirimlere izin verin.',
    off: 'Kapalı',
    on: 'Açık',
    enable: 'Bildirimleri aç',
    enabling: 'Açılıyor…',
    disable: 'Bildirimleri kapat',
    test: 'Test bildirimi gönder',
    testing: 'Gönderiliyor…',
    testSent: 'Test bildirimi gönderildi. Birkaç saniye içinde gelmeli.',
    testNoDevice: 'Bu hesap için kayıtlı cihaz yok. Önce bildirimleri açın.',
    missingKey: 'Bildirim anahtarı yapılandırılmamış (VITE_VAPID_PUBLIC_KEY).',
    error: 'Bildirim ayarı değiştirilemedi.',
    explain: 'Yeni antrenman, yoklama süresi ve program duyurularından haberdar olun.',
  },

  install: {
    title: 'Uygulamayı telefonunuza yükleyin',
    installedTitle: 'Uygulama yüklü',
    installedBody: 'Ana ekrandaki simgeden açıyorsunuz. Harika!',
    body: 'Mağazadan indirmeniz gerekmez. Ana ekrana ekleyin; uygulama gibi açılır ve bildirim alabilirsiniz.',
    installButton: 'Yükle',
    iosTitle: 'iPhone (Safari)',
    iosSteps: [
      'Bu sayfayı Safari\'de açın (Chrome değil).',
      'Alttaki Paylaş düğmesine (kare ve yukarı ok) dokunun.',
      '"Ana Ekrana Ekle"yi seçin ve Ekle\'ye dokunun.',
      'Ana ekrandaki "Kürek" simgesinden açın; sonra Profil → Bildirimleri aç.',
    ],
    iosNote: 'Bildirimler için iPhone\'unuzda iOS 16.4 veya üstü gerekir.',
    androidTitle: 'Android (Chrome)',
    androidSteps: [
      'Sağ üstteki ⋮ menüsüne dokunun.',
      '"Uygulamayı yükle" veya "Ana ekrana ekle"yi seçin.',
      'Ana ekrandaki "Kürek" simgesinden açın.',
    ],
    dismiss: 'Şimdilik gizle',
    seeSteps: 'Nasıl yapılır?',
    otherTitle: 'Diğer tarayıcılar',
    otherBody: 'Tarayıcı menüsünden "Uygulamayı yükle" veya "Ana ekrana ekle" seçeneğini arayın.',
  },

  profile: {
    title: 'Profil',
    account: 'Hesap',
    changePassword: 'Şifremi değiştir',
    privacy: 'Gizlilik bildirimi',
    version: 'Sürüm',
  },

  more: {
    title: 'Diğer',
    boats: 'Tekneler',
    clubSettings: 'Kulüp ayarları',
  },

  privacy: {
    title: 'Gizlilik bildirimi',
    draftNotice: 'Taslak metin — yayına almadan önce kulüp yönetimi tarafından onaylanmalıdır.',
    sections: [
      {
        heading: 'Hangi bilgiler tutuluyor?',
        body: 'Ad soyad, kullanıcı adı, isteğe bağlı telefon numarası, antrenman katılım yanıtları, yoklama kayıtları ve bildirim cihaz bilgileri.',
      },
      {
        heading: 'Neden tutuluyor?',
        body: 'Yalnızca kulüp antrenmanlarını planlamak, tekne programını duyurmak, katılımı takip etmek ve aylık istatistik üretmek için.',
      },
      {
        heading: 'Kimler görebilir?',
        body: 'Antrenörler tüm kayıtları görür. Üyeler yalnızca kendi kayıtlarını, yayınlanmış programı ve diğer üyelerin ad soyadını (sıralama ve tekne ekibi için) görür. Telefon ve kullanıcı adı diğer üyelere gösterilmez.',
      },
      {
        heading: 'Verileriniz üzerindeki haklarınız',
        body: 'Bilgilerinizin düzeltilmesini veya silinmesini antrenörlerinizden isteyebilirsiniz.',
      },
    ],
  },

  trainings: {
    title: 'Antrenmanlar',
    tabUpcoming: 'Yaklaşan',
    tabPast: 'Geçmiş',
    add: 'Antrenman ekle',
    newTitle: 'Yeni antrenman',
    editTitle: 'Antrenmanı düzenle',
    edit: 'Düzenle',
    cancelAction: 'İptal et',
    statusCancelled: 'İptal edildi',
    statusCompleted: 'Tamamlandı',
    emptyUpcomingTitle: 'Yaklaşan antrenman yok',
    emptyUpcomingMember: 'Yeni bir antrenman eklendiğinde burada göreceksiniz.',
    emptyUpcomingCoach: 'İlk antrenmanı eklemek için "Antrenman ekle" düğmesine dokunun.',
    emptyPastTitle: 'Geçmiş antrenman yok',
    emptyPastBody: 'Tamamlanan antrenmanlar burada listelenir.',
    loadError: 'Antrenmanlar yüklenemedi.',
    notFoundTitle: 'Antrenman bulunamadı',
    notFoundBody: 'Bu antrenman silinmiş veya erişiminiz yok.',
    back: 'Antrenmanlar',
    deadlineLabel: (text: string) => `Son yanıt: ${text}`,
    summary: (attending: number, notAttending: number, none: number) =>
      `${attending} katılıyor · ${notAttending} katılmıyor · ${none} yanıt yok`,
    tabResponses: 'Yanıtlar',
    tabProgram: 'Program',
    tabAttendance: 'Yoklama',
    tabsLabel: 'Antrenman bölümleri',
    cancelReasonShown: (reason: string) => `İptal nedeni: ${reason}`,
    created: 'Antrenman oluşturuldu.',
    updated: 'Antrenman güncellendi.',
    notesHeading: 'Antrenör notu',
    attendancePlaceholderCoach: 'Antrenman sonrası yoklama bir sonraki aşamada eklenecek.',
    notEditableTitle: 'Bu antrenman düzenlenemez',
    notEditableBody: 'İptal edilmiş veya tamamlanmış antrenmanlar değiştirilemez.',
    form: {
      titleLabel: 'Başlık',
      titleHint: 'İsteğe bağlı. Ör. "Sabah antrenmanı"',
      titleTooLong: 'Başlık en fazla 80 karakter olabilir.',
      date: 'Tarih',
      dateRequired: 'Tarih seçin.',
      dateInvalid: 'Geçerli bir tarih ve saat girin.',
      startTime: 'Başlangıç saati',
      timeRequired: 'Saat seçin.',
      startInPast: 'Başlangıç zamanı geçmişte olamaz.',
      sessions: 'Seans sayısı',
      sessionsHint: '1 seans = 1 saat. Örneğin 08:00 başlangıç ve 2 seans, 08:00–10:00 demektir.',
      sessionsRequired: 'Seans sayısı 1 ile 6 arasında olmalı.',
      sessionOption: (n: number) => `${n} seans (${n} saat)`,
      deadline: 'Son yanıt zamanı',
      deadlineHint: 'Üyeler bu zamandan sonra katılım yanıtlarını değiştiremez.',
      deadlinePreset: (hours: number) => `${hours} saat önce`,
      deadlineCustom: 'Özel zaman',
      deadlineDate: 'Son yanıt tarihi',
      deadlineTimeLabel: 'Son yanıt saati',
      deadlineRequired: 'Son yanıt tarihini ve saatini girin.',
      deadlineAfterStart: 'Son yanıt zamanı antrenman başlangıcından sonra olamaz.',
      deadlineInPast: 'Son yanıt zamanı geçmişte olamaz. Daha erken bir süre seçin veya başlangıcı ileri alın.',
      notes: 'Notlar',
      notesHint: 'İsteğe bağlı. Üyeler antrenman ayrıntısında görür.',
      notesTooLong: 'Notlar en fazla 500 karakter olabilir.',
      preview: (range: string, deadline: string) => `Antrenman ${range} · Son yanıt: ${deadline}`,
      save: 'Kaydet',
      create: 'Antrenmanı oluştur',
      saving: 'Kaydediliyor…',
    },
    cancel: {
      title: 'Antrenmanı iptal et',
      body: 'Üyeler antrenmanın iptal edildiğini ve nedenini görecek. Bu işlem geri alınamaz.',
      reasonLabel: 'İptal nedeni',
      reasonHint: 'Ör. "Şiddetli rüzgâr" (3–200 karakter)',
      reasonInvalid: 'İptal nedeni 3–200 karakter olmalı.',
      confirm: 'Antrenmanı iptal et',
      confirming: 'İptal ediliyor…',
      keep: 'Vazgeç',
      done: 'Antrenman iptal edildi.',
    },
  },

  rsvp: {
    question: 'Bu antrenmana katılacak mısınız?',
    attending: 'Katılıyorum',
    notAttending: 'Katılmıyorum',
    groupLabel: 'Katılım durumu',
    yourAnswer: (answer: string) => `Yanıtınız: ${answer}`,
    noAnswerYet: 'Henüz yanıt vermediniz.',
    awaiting: 'Yanıt bekleniyor',
    noteLabel: 'Antrenöre not',
    notePlaceholder: 'Ör. 09:00\'dan sonraya yazar mısınız? İşim var.',
    noteHint:
      '"Katılıyorum", o gün hangi saate yazılırsanız yazılın orada olacağınız anlamına gelir. Özel bir isteğiniz varsa buraya yazın.',
    noteTooLong: 'Not en fazla 200 karakter olabilir.',
    saveNote: 'Notu kaydet',
    saving: 'Kaydediliyor…',
    saved: 'Yanıtınız kaydedildi.',
    lockedTitle: 'Yanıt süresi doldu',
    lockedBody: 'Değişiklik yapmak için antrenörünüzle görüşün.',
    lockedNoAnswer: 'Süre içinde yanıt vermediniz.',
    cancelledTitle: 'Bu antrenman iptal edildi',
    completedTitle: 'Bu antrenman tamamlandı',
    enteredByCoach: 'Antrenör tarafından kaydedildi',
    yourNote: 'Notunuz',
    deadlineAt: (text: string) => `Son yanıt: ${text}`,
  },

  responses: {
    attendingHeading: 'Katılıyor',
    notAttendingHeading: 'Katılmıyor',
    noResponseHeading: 'Yanıt yok',
    nobody: 'Kimse yok',
    noMembers: 'Henüz üye yok. Önce Üyeler sayfasından üye ekleyin.',
    deadlineOpen: (countdown: string) => `Yanıt süresi: ${countdown}`,
    deadlineClosed: 'Yanıt süresi doldu',
    coachEntered: 'Antrenör girdi',
    overrideTitle: 'Yanıtı kaydet',
    overrideHelp: 'Üye adına yanıt girin (ör. telefonla bildirdi). Süre dolmuş olsa da çalışır.',
    overrideSaved: 'Yanıt kaydedildi.',
    loadError: 'Yanıtlar yüklenemedi.',
    rowAction: (name: string) => `${name} için yanıtı değiştir`,
  },

  program: {
    heading: 'Antrenman programı',
    // --- member ---
    notPublishedTitle: 'Program henüz yayınlanmadı',
    notPublishedBody: 'Antrenör tekne ve ekip programını yayınladığında burada göreceksiniz.',
    yours: 'Sizin programınız',
    yourNoneAttending: 'Katılacağınızı bildirdiniz ama henüz bir tekneye atanmadınız. Antrenörünüzle görüşün.',
    you: 'Siz',
    fullProgram: 'Tüm program',
    slotHeading: (n: number, range: string) => `${n}. seans · ${range}`,
    noBoats: 'Bu seansta tekne yok',
    weather: 'Hava durumu',
    trainingNotes: 'Antrenman notu',
    formerMember: 'Eski üye',
    seeProgram: 'Programı gör',
    loadError: 'Program yüklenemedi.',
    boatNote: 'Not',
    // --- coach ---
    slotsLabel: 'Seanslar',
    crewCount: (n: number, capacity: number) => `${n}/${capacity}`,
    pickCrew: 'Ekip seç',
    editCrew: 'Ekibi düzenle',
    removeFromBoat: (name: string) => `${name} ekipten çıkar`,
    boatInactive: 'Kullanım dışı',
    copyPrevious: 'Önceki seansı kopyala',
    clearSlot: 'Seansı temizle',
    copyConfirmTitle: 'Bu seansın atamaları değişsin mi?',
    copyConfirmBody: 'Bu seansta zaten atamalar var. Önceki seanstaki tekneler ve ekipler bunların yerine geçecek.',
    copyConfirm: 'Evet, kopyala',
    clearConfirmTitle: 'Bu seans temizlensin mi?',
    clearConfirmBody: 'Bu seanstaki tüm tekne atamaları kaldırılır. Kaydedene kadar üyeler etkilenmez.',
    clearConfirm: 'Evet, temizle',
    boatNoteLabel: 'Tekne notu (isteğe bağlı)',
    weatherNote: 'Hava durumu notu',
    weatherNoteHint: 'Ör. "Rüzgâr batıdan 15 km/s, dalga düşük". Üyeler görür.',
    trainingNotesLabel: 'Antrenman notu',
    trainingNotesHint: 'Ör. ısınma, tempo, dönüş noktaları. Üyeler görür.',
    statusDraft: 'Taslak — üyeler görmüyor',
    statusPublished: (version: number) => `Yayında (sürüm ${version})`,
    unsaved: 'Kaydedilmemiş değişiklikler var',
    upToDate: 'Tüm değişiklikler kaydedildi',
    saveDraft: 'Taslağı kaydet',
    publish: 'Yayınla',
    update: 'Güncelle',
    unpublish: 'Yayından kaldır',
    saving: 'Kaydediliyor…',
    draftSaved: 'Taslak kaydedildi.',
    publishedToast: 'Program yayınlandı.',
    updatedToast: 'Program güncellendi.',
    unpublishedToast: 'Program yayından kaldırıldı.',
    unpublishConfirmTitle: 'Program yayından kaldırılsın mı?',
    unpublishConfirmBody: 'Üyeler programı artık göremez. Şu anki düzenlemeleriniz taslak olarak kaydedilir.',
    emptyPublish: 'Yayınlamak için en az bir tekneye ekip atayın.',
    summaryHeading: 'Katılım özeti',
    summaryHint: '"Katılıyorum" diyenler ve hangi seanslarda yer aldıkları.',
    noSessions: 'Hiç seansta yok',
    seasonCount: (n: number) => `${n} seans`,
    noAnswerTag: 'Yanıt yok',
    notAttendingTag: 'Katılmıyor',
    noNotes: 'Not yok',
    // picker
    pickerTitle: (boat: string, range: string) => `${boat} · ${range}`,
    pickerHint: 'Ekibe eklemek veya çıkarmak için dokunun.',
    pickerDone: 'Tamam',
    attendingGroup: 'Katılıyor',
    noAnswerGroup: 'Yanıt vermedi',
    notAttendingGroup: 'Katılmıyor',
    otherMembers: 'Yanıt vermeyenler ve katılmayanlar',
    inOtherBoat: (boat: string) => `Bu seansta ${boat} teknesinde`,
    boatFull: 'Tekne dolu',
    noMembersToPick: 'Seçilebilecek üye yok.',
    // warnings
    warnTitle: 'Yayınlamadan önce',
    warnUnassigned: (names: string) => `${names} hiçbir seansa atanmadı.`,
    warnNotAttending: (names: string) => `${names} "Katılmıyorum" demişti ama programda.`,
    warnNoAnswer: (names: string) => `${names} henüz yanıt vermedi ama programda.`,
    warnQuestion: 'Yine de devam edilsin mi?',
    publishAnyway: 'Yine de yayınla',
    updateAnyway: 'Yine de güncelle',
    backToEditing: 'Düzenlemeye dön',
    // leaving
    leaveTitle: 'Kaydedilmemiş değişiklikler',
    leaveBody: 'Bu sayfadan çıkarsanız yaptığınız değişiklikler kaybolur.',
    leaveStay: 'Kal',
    leaveGo: 'Kaydetmeden çık',
    // states
    needBoats: 'Önce tekne ekleyin',
    needBoatsBody: 'Program hazırlamak için Diğer → Tekneler bölümünden en az bir kullanımdaki tekne olmalı.',
    needBoatsAction: 'Teknelere git',
    readOnly: 'Bu antrenmanın programı artık düzenlenemez.',
    noProgramYet: 'Bu antrenman için program hazırlanmadı.',
  },

  boats: {
    title: 'Tekneler',
    add: 'Tekne ekle',
    newTitle: 'Yeni tekne',
    editTitle: 'Tekneyi düzenle',
    name: 'Tekne adı',
    nameRequired: 'Tekne adı 1–40 karakter olmalı.',
    capacity: 'Kişi kapasitesi',
    capacityOption: (n: number) => `${n} kişilik`,
    active: 'Kullanımda',
    inactive: 'Kullanım dışı',
    activeLabel: 'Tekne kullanımda',
    activeHint: 'Kullanım dışı tekneler antrenman programında seçilemez.',
    duplicate: 'Bu isimde bir tekne zaten var.',
    saved: 'Tekne kaydedildi.',
    save: 'Kaydet',
    saving: 'Kaydediliyor…',
    emptyTitle: 'Henüz tekne yok',
    emptyBody: 'Program hazırlayabilmek için en az bir tekne ekleyin.',
    loadError: 'Tekneler yüklenemedi.',
    back: 'Diğer',
  },

  notFound: {
    title: 'Sayfa bulunamadı',
    body: 'Aradığınız sayfa yok veya taşınmış olabilir.',
    home: 'Ana sayfaya dön',
  },
} as const;
