// All user-facing copy lives here (Turkish only, by club decision). Keeping strings in one typed
// catalog means no scattered literals, consistent wording, and one place for the club to review.

export const tr = {
  app: {
    name: 'Yeni Mahalle Kürek',
    clubName: 'Kdz. Ereğli Yeni Mahalle Kürek Kulübü',
    loading: 'Yükleniyor…',
  },

  common: {
    retry: 'Tekrar dene',
    cancel: 'Vazgeç',
    close: 'Kapat',
    copy: 'Kopyala',
    copied: 'Kopyalandı',
    share: 'Paylaş',
    search: 'Ara',
    show: 'Göster',
    hide: 'Gizle',
    optional: 'isteğe bağlı',
    errorTitle: 'Bir sorun oluştu',
    errorGeneric: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
    errorNetwork: 'Bağlantı kurulamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.',
    soonTitle: 'Yakında',
    soonBody: 'Bu bölüm sonraki aşamada eklenecek.',
    forbidden: 'Bu işlem için yetkiniz yok.',
    save: 'Kaydet',
    edit: 'Düzenle',
    tabsLabel: 'Bölümler',
    offline: 'Çevrimdışısınız. Görünen bilgiler güncel olmayabilir.',
    updateAvailable: 'Yeni sürüm hazır.',
    updateAction: 'Yenile',
  },

  config: {
    title: 'Uygulama yapılandırılmamış',
    body: 'Aşağıdaki ayarlar eksik veya hatalı. docs/RUNBOOK.md dosyasındaki adımları izleyin.',
  },

  auth: {
    loginTitle: 'Giriş yap',
    loginSubtitle: 'Antrenörünüzün verdiği kullanıcı adı ve şifre ile giriş yapın.',
    username: 'Kullanıcı adı',
    password: 'Şifre',
    submit: 'Giriş yap',
    submitting: 'Giriş yapılıyor…',
    usernameRequired: 'Kullanıcı adınızı yazın.',
    passwordRequired: 'Şifrenizi yazın.',
    invalidCredentials: 'Kullanıcı adı veya şifre hatalı.',
    accountDisabled: 'Hesabınız devre dışı bırakılmış. Lütfen antrenörünüzle görüşün.',
    tooManyAttempts: 'Çok fazla deneme yaptınız. Birkaç dakika sonra tekrar deneyin.',
    noAccount: 'Hesabınız yok mu? Hesapları antrenörler oluşturur; antrenörünüzle iletişime geçin.',
    logout: 'Çıkış yap',
    blockedTitle: 'Hesabınıza erişilemiyor',
    blockedBody: 'Hesabınız devre dışı bırakılmış veya bulunamadı. Lütfen antrenörünüzle görüşün.',
    changePasswordTitle: 'Yeni şifre belirleyin',
    changePasswordForced: 'Güvenliğiniz için geçici şifrenizi değiştirmeniz gerekiyor.',
    newPassword: 'Yeni şifre',
    confirmPassword: 'Yeni şifre (tekrar)',
    passwordRules: 'En az 8 karakter; harf ve rakam içermeli.',
    passwordTooShort: 'Şifre en az 8 karakter olmalı.',
    passwordNeedsLetterAndDigit: 'Şifre hem harf hem rakam içermeli.',
    passwordMismatch: 'Şifreler eşleşmiyor.',
    passwordSame: 'Yeni şifre mevcut şifrenizle aynı olamaz.',
    passwordWeak: 'Bu şifre çok zayıf. Daha güçlü bir şifre seçin.',
    passwordChanged: 'Şifreniz değiştirildi.',
    savePassword: 'Şifreyi kaydet',
    saving: 'Kaydediliyor…',
  },

  nav: {
    home: 'Ana Sayfa',
    trainings: 'Antrenmanlar',
    stats: 'İstatistik',
    profile: 'Profil',
    dashboard: 'Panel',
    members: 'Üyeler',
    more: 'Diğer',
    mainNav: 'Ana gezinme',
  },

  roles: {
    coach: 'Antrenör',
    member: 'Üye',
  },

  home: {
    greeting: (name: string) => `Merhaba, ${name}`,
    noUpcomingTitle: 'Yaklaşan antrenman yok',
    noUpcomingBody: 'Yeni bir antrenman eklendiğinde burada göreceksiniz.',
    coachNoUpcomingBody: 'İlk antrenmanı eklemek için "Antrenman ekle" düğmesine dokunun.',
    nextTraining: 'Sıradaki antrenman',
    otherUpcoming: 'Diğer yaklaşan antrenmanlar',
    coachUpcoming: 'Yaklaşan antrenmanlar',
    seeAll: 'Tümünü gör',
    manageMembers: 'Üyeleri yönet',
  },

  members: {
    title: 'Üyeler',
    add: 'Üye ekle',
    searchPlaceholder: 'İsim veya kullanıcı adı ara',
    emptyTitle: 'Henüz üye yok',
    emptyBody: 'İlk üyeyi eklemek için "Üye ekle" düğmesine dokunun.',
    noResults: 'Aramanızla eşleşen üye yok.',
    loadError: 'Üye listesi yüklenemedi.',
    inactive: 'Devre dışı',
    neverLoggedIn: 'İlk giriş bekleniyor',
    fullName: 'Ad soyad',
    phone: 'Telefon',
    phoneHint: 'Kulüpteki diğer üyeler bu numarayı görebilir.',
    fullNameRequired: 'Ad soyad en az 2 karakter olmalı.',
    usernameHint: 'Küçük harf (a-z), rakam, nokta, tire veya alt çizgi; 3–30 karakter.',
    usernameInvalid: 'Kullanıcı adı 3–30 karakter olmalı; yalnızca a-z, 0-9, nokta, tire ve alt çizgi.',
    roleLabel: 'Rol',
    createTitle: 'Yeni üye ekle',
    create: 'Hesabı oluştur',
    creating: 'Oluşturuluyor…',
    credentialsTitle: 'Hesap hazır',
    credentialsWarning: 'Bu şifre yalnızca bir kez gösterilir. Şimdi kopyalayıp üyeye iletin; üye ilk girişte yeni şifre belirleyecek.',
    credentialsUsername: 'Kullanıcı adı',
    credentialsPassword: 'Geçici şifre',
    copyInvite: 'Davet mesajını kopyala',
    inviteMessage: (appUrl: string, username: string, password: string) =>
      `Yeni Mahalle Kürek uygulaması\nAdres: ${appUrl}\nKullanıcı adı: ${username}\nGeçici şifre: ${password}\n(İlk girişte yeni şifre belirlemeniz istenecek.)`,
    detailsTitle: 'Üye işlemleri',
    resetPassword: 'Şifreyi sıfırla',
    resetConfirm: 'Yeni bir geçici şifre oluşturulsun mu? Eski şifre geçersiz olur.',
    resetDone: 'Şifre sıfırlandı',
    deactivate: 'Hesabı devre dışı bırak',
    deactivateConfirm: 'Bu kişi artık giriş yapamayacak. Geçmiş kayıtları korunur. Devam edilsin mi?',
    activate: 'Hesabı yeniden etkinleştir',
    confirmAction: 'Evet, devam et',
    activated: 'Hesap etkinleştirildi.',
    deactivated: 'Hesap devre dışı bırakıldı.',
    you: 'Siz',
  },

  push: {
    title: 'Bildirimler',
    unsupportedBrowser: 'Bu tarayıcı bildirimleri desteklemiyor.',
    iosNeedsInstall:
      'iPhone\'da bildirim almak için önce uygulamayı ana ekrana eklemeniz gerekir (aşağıdaki adımlara bakın).',
    denied: 'Bildirimler engellenmiş. Telefonunuzun ayarlarından bu uygulama için bildirimlere izin verin.',
    off: 'Kapalı',
    on: 'Açık',
    enable: 'Bildirimleri aç',
    enabling: 'Açılıyor…',
    disable: 'Bildirimleri kapat',
    test: 'Test bildirimi gönder',
    testing: 'Gönderiliyor…',
    testSent: 'Test bildirimi gönderildi. Birkaç saniye içinde gelmeli.',
    testNoDevice: 'Bu hesap için kayıtlı cihaz yok. Önce bildirimleri açın.',
    missingKey: 'Bildirim anahtarı yapılandırılmamış (VITE_VAPID_PUBLIC_KEY).',
    error: 'Bildirim ayarı değiştirilemedi.',
    explain: 'Yeni antrenman, yoklama süresi ve program duyurularından haberdar olun.',
  },

  install: {
    title: 'Uygulamayı telefonunuza yükleyin',
    installedTitle: 'Uygulama yüklü',
    installedBody: 'Ana ekrandaki simgeden açıyorsunuz. Harika!',
    body: 'Mağazadan indirmeniz gerekmez. Ana ekrana ekleyin; uygulama gibi açılır ve bildirim alabilirsiniz.',
    installButton: 'Yükle',
    iosTitle: 'iPhone (Safari)',
    iosSteps: [
      'Bu sayfayı Safari\'de açın (Chrome değil).',
      'Alttaki Paylaş düğmesine (kare ve yukarı ok) dokunun.',
      '"Ana Ekrana Ekle"yi seçin ve Ekle\'ye dokunun.',
      'Ana ekrandaki "Kürek" simgesinden açın; sonra Profil → Bildirimleri aç.',
    ],
    iosNote: 'Bildirimler için iPhone\'unuzda iOS 16.4 veya üstü gerekir.',
    androidTitle: 'Android (Chrome)',
    androidSteps: [
      'Sağ üstteki ⋮ menüsüne dokunun.',
      '"Uygulamayı yükle" veya "Ana ekrana ekle"yi seçin.',
      'Ana ekrandaki "Kürek" simgesinden açın.',
    ],
    dismiss: 'Şimdilik gizle',
    seeSteps: 'Nasıl yapılır?',
    otherTitle: 'Diğer tarayıcılar',
    otherBody: 'Tarayıcı menüsünden "Uygulamayı yükle" veya "Ana ekrana ekle" seçeneğini arayın.',
  },

  profile: {
    title: 'Profil',
    account: 'Hesap',
    changePassword: 'Şifremi değiştir',
    clubMembers: 'Kulüp üyeleri',
    privacy: 'Gizlilik bildirimi',
    version: 'Sürüm',
  },

  more: {
    title: 'Diğer',
    boats: 'Tekneler',
    clubSettings: 'Kulüp ayarları',
    audit: 'Değişiklik geçmişi',
  },

  privacy: {
    title: 'Gizlilik bildirimi',
    draftNotice: 'Taslak metin — yayına almadan önce kulüp yönetimi tarafından onaylanmalıdır.',
    sections: [
      {
        heading: 'Hangi bilgiler tutuluyor?',
        body: 'Ad soyad, kullanıcı adı, isteğe bağlı telefon numarası, antrenman katılım yanıtları, yoklama kayıtları ve bildirim cihaz bilgileri.',
      },
      {
        heading: 'Neden tutuluyor?',
        body: 'Yalnızca kulüp antrenmanlarını planlamak, tekne programını duyurmak, katılımı takip etmek ve aylık istatistik üretmek için.',
      },
      {
        heading: 'Kimler görebilir?',
        body: 'Antrenörler tüm kayıtları görür. Üyeler kendi kayıtlarını, yayınlanmış programı ve diğer üyelerin ad soyadını ve telefon numarasını (antrenman arkadaşlarınıza ulaşabilmeniz için) görür. Kullanıcı adı, katılım yanıtları ve yoklama kayıtları diğer üyelere gösterilmez; aylık sıralamada yalnızca seans sayısı görünür.',
      },
      {
        heading: 'Değişiklik kayıtları',
        body: 'Antrenörlerin yaptığı değişiklikler (ör. antrenman düzenleme, program yayınlama, yoklama kaydetme, hesap işlemleri) kimin ne zaman yaptığıyla birlikte bir yıl saklanır ve yalnızca antrenörler görür. Şifreler ve telefon numaraları bu kayıtlara yazılmaz.',
      },
      {
        heading: 'Verileriniz üzerindeki haklarınız',
        body: 'Bilgilerinizin düzeltilmesini veya silinmesini antrenörlerinizden isteyebilirsiniz.',
      },
    ],
  },

  trainings: {
    title: 'Antrenmanlar',
    tabUpcoming: 'Yaklaşan',
    tabPast: 'Geçmiş',
    add: 'Antrenman ekle',
    newTitle: 'Yeni antrenman',
    editTitle: 'Antrenmanı düzenle',
    edit: 'Düzenle',
    cancelAction: 'İptal et',
    statusCancelled: 'İptal edildi',
    statusCompleted: 'Tamamlandı',
    durationUnknown: 'süre program hazırlanınca belli olur',
    emptyUpcomingTitle: 'Yaklaşan antrenman yok',
    emptyUpcomingMember: 'Yeni bir antrenman eklendiğinde burada göreceksiniz.',
    emptyUpcomingCoach: 'İlk antrenmanı eklemek için "Antrenman ekle" düğmesine dokunun.',
    emptyPastTitle: 'Geçmiş antrenman yok',
    emptyPastBody: 'Tamamlanan antrenmanlar burada listelenir.',
    showOlder: 'Daha eski antrenmanları göster',
    olderNone: 'Daha eski antrenman yok.',
    olderHeading: 'Daha eski',
    loadError: 'Antrenmanlar yüklenemedi.',
    notFoundTitle: 'Antrenman bulunamadı',
    notFoundBody: 'Bu antrenman silinmiş veya erişiminiz yok.',
    back: 'Antrenmanlar',
    deadlineLabel: (text: string) => `Son yanıt: ${text}`,
    summary: (attending: number, notAttending: number, none: number) =>
      `${attending} katılıyor · ${notAttending} katılmıyor · ${none} yanıt yok`,
    tabResponses: 'Yanıtlar',
    tabProgram: 'Program',
    tabAttendance: 'Yoklama',
    tabsLabel: 'Antrenman bölümleri',
    cancelReasonShown: (reason: string) => `İptal nedeni: ${reason}`,
    created: 'Antrenman oluşturuldu.',
    updated: 'Antrenman güncellendi.',
    notesHeading: 'Antrenör notu',
    notEditableTitle: 'Bu antrenman düzenlenemez',
    notEditableBody: 'İptal edilmiş veya tamamlanmış antrenmanlar değiştirilemez.',
    form: {
      titleLabel: 'Başlık',
      titleHint: 'İsteğe bağlı. Ör. "Sabah antrenmanı"',
      titleTooLong: 'Başlık en fazla 80 karakter olabilir.',
      date: 'Tarih',
      dateRequired: 'Tarih seçin.',
      dateInvalid: 'Geçerli bir tarih ve saat girin.',
      startTime: 'Başlangıç saati',
      timeRequired: 'Saat seçin.',
      startInPast: 'Başlangıç zamanı geçmişte olamaz.',
      sessionsInfo: 'Kaç seans süreceğini şimdi girmenize gerek yok. Programı hazırlarken gerektiği kadar seans (1 seans = 1 saat) eklersiniz.',
      deadline: 'Son yanıt zamanı',
      deadlineHint: 'Üyeler bu zamandan sonra — veya program yayınlandığında — katılım yanıtlarını değiştiremez.',
      deadlinePreset: (hours: number) => `${hours} saat önce`,
      deadlineEvening: 'Bir önceki akşam 20:00',
      deadlineCustom: 'Özel zaman',
      deadlineDate: 'Son yanıt tarihi',
      deadlineTimeLabel: 'Son yanıt saati',
      deadlineRequired: 'Son yanıt tarihini ve saatini girin.',
      deadlineAfterStart: 'Son yanıt zamanı antrenman başlangıcından sonra olamaz.',
      deadlineInPast: 'Son yanıt zamanı geçmişte olamaz. Daha erken bir süre seçin veya başlangıcı ileri alın.',
      notes: 'Notlar',
      notesHint: 'İsteğe bağlı. Üyeler antrenman ayrıntısında görür.',
      notesTooLong: 'Notlar en fazla 500 karakter olabilir.',
      preview: (range: string, deadline: string) => `Antrenman ${range} · Son yanıt: ${deadline}`,
      save: 'Kaydet',
      create: 'Antrenmanı oluştur',
      saving: 'Kaydediliyor…',
    },
    cancel: {
      title: 'Antrenmanı iptal et',
      body: 'Üyeler antrenmanın iptal edildiğini ve nedenini görecek. Bu işlem geri alınamaz.',
      reasonLabel: 'İptal nedeni',
      reasonHint: 'Ör. "Şiddetli rüzgâr" (3–200 karakter)',
      reasonInvalid: 'İptal nedeni 3–200 karakter olmalı.',
      confirm: 'Antrenmanı iptal et',
      confirming: 'İptal ediliyor…',
      keep: 'Vazgeç',
      done: 'Antrenman iptal edildi.',
    },
  },

  rsvp: {
    question: 'Bu antrenmana katılacak mısınız?',
    attending: 'Katılıyorum',
    notAttending: 'Katılmıyorum',
    groupLabel: 'Katılım durumu',
    yourAnswer: (answer: string) => `Yanıtınız: ${answer}`,
    noAnswerYet: 'Henüz yanıt vermediniz.',
    awaiting: 'Yanıt bekleniyor',
    noteLabel: 'Antrenöre not',
    notePlaceholder: 'Ör. 09:00\'dan sonraya yazar mısınız? İşim var.',
    noteHint:
      '"Katılıyorum", o gün hangi saate yazılırsanız yazılın orada olacağınız anlamına gelir. Özel bir isteğiniz varsa buraya yazın.',
    noteTooLong: 'Not en fazla 200 karakter olabilir.',
    saveNote: 'Notu kaydet',
    saving: 'Kaydediliyor…',
    saved: 'Yanıtınız kaydedildi.',
    lockedTitle: 'Yanıt süresi doldu',
    lockedBody: 'Değişiklik yapmak için antrenörünüzle görüşün.',
    lockedProgramTitle: 'Program yayınlandı, yanıtlar kilitlendi',
    lockedProgramBody: 'Program yayınlandıktan sonra katılım yanıtı değiştirilemez. Değişiklik için antrenörünüzle görüşün.',
    lockedNoAnswer: 'Süre içinde yanıt vermediniz.',
    cancelledTitle: 'Bu antrenman iptal edildi',
    completedTitle: 'Bu antrenman tamamlandı',
    enteredByCoach: 'Antrenör tarafından kaydedildi',
    yourNote: 'Notunuz',
    deadlineAt: (text: string) => `Son yanıt: ${text}`,
  },

  responses: {
    attendingHeading: 'Katılıyor',
    notAttendingHeading: 'Katılmıyor',
    noResponseHeading: 'Yanıt yok',
    nobody: 'Kimse yok',
    noMembers: 'Henüz üye yok. Önce Üyeler sayfasından üye ekleyin.',
    deadlineOpen: (countdown: string) => `Yanıt süresi: ${countdown}`,
    deadlineClosed: 'Yanıt süresi doldu',
    lockedByProgram: 'Program yayınlandı — üyeler artık yanıtlarını değiştiremez (siz değiştirebilirsiniz).',
    coachEntered: 'Antrenör girdi',
    overrideTitle: 'Yanıtı kaydet',
    overrideHelp: 'Üye adına yanıt girin (ör. telefonla bildirdi). Süre dolmuş olsa da çalışır.',
    overrideSaved: 'Yanıt kaydedildi.',
    loadError: 'Yanıtlar yüklenemedi.',
    rowAction: (name: string) => `${name} için yanıtı değiştir`,
  },

  program: {
    heading: 'Antrenman programı',
    // --- member ---
    notPublishedTitle: 'Program henüz yayınlanmadı',
    notPublishedBody: 'Antrenör tekne ve ekip programını yayınladığında burada göreceksiniz.',
    yours: 'Sizin programınız',
    yourNoneAttending: 'Katılacağınızı bildirdiniz ama henüz bir tekneye atanmadınız. Antrenörünüzle görüşün.',
    you: 'Siz',
    fullProgram: 'Tüm program',
    fullProgramHint: 'Tekne tekne tüm seanslar ve ekipler. Sizin seanslarınız vurgulanır.',
    yourSession: 'Sizin seansınız',
    yourBoat: 'Sizin tekneniz',
    boatProgram: (boat: string) => `${boat} programı`,
    contactAbout: (name: string) => `${name} — telefon numarasını göster`,
    slotHeading: (n: number, range: string) => `${n}. seans · ${range}`,
    noBoats: 'Bu seansta tekne yok',
    weather: 'Hava durumu',
    trainingNotes: 'Antrenman notu',
    formerMember: 'Eski üye',
    loadError: 'Program yüklenemedi.',
    boatNote: 'Not',
    // --- coach ---
    slotsLabel: 'Seanslar',
    addSession: 'Seans ekle',
    removeSession: 'Son seansı kaldır',
    removeSessionTitle: 'Son seans kaldırılsın mı?',
    removeSessionBody: 'Bu seanstaki tüm tekne atamaları da kaldırılır. Kaydedene kadar üyeler etkilenmez.',
    removeSessionConfirm: 'Evet, kaldır',
    sessionsHint: 'Antrenman kaç saat sürecekse o kadar seans ekleyin (1 seans = 1 saat). Süre, programdan belli olur.',
    maxSessions: (n: number) => `Bir antrenman en fazla ${n} seans olabilir.`,
    sessionTotal: (n: number) => `Antrenman şu an ${n} seans (${n} saat) sürüyor.`,
    fullCrewBadge: (capacity: number) => `Tam ${capacity} kişi gerekli`,
    fullCrewProblem: (boat: string, slot: number, count: number, capacity: number) =>
      `${boat}, ${slot}. seans: ${count}/${capacity} kişi — tam ${capacity} kişi olmalı.`,
    fullCrewBlockedTitle: 'Yayınlanamıyor: eksik veya fazla ekip',
    fullCrewBlockedBody: 'Şu tekneler her seansta tam kadro olmalı. Ekibi tamamlayın veya tekneyi o seanstan çıkarın:',
    crewCount: (n: number, capacity: number) => `${n}/${capacity}`,
    pickCrew: 'Ekip seç',
    editCrew: 'Ekibi düzenle',
    removeFromBoat: (name: string) => `${name} ekipten çıkar`,
    boatInactive: 'Kullanım dışı',
    copyPrevious: 'Önceki seansı kopyala',
    clearSlot: 'Seansı temizle',
    copyConfirmTitle: 'Bu seansın atamaları değişsin mi?',
    copyConfirmBody: 'Bu seansta zaten atamalar var. Önceki seanstaki tekneler ve ekipler bunların yerine geçecek.',
    copyConfirm: 'Evet, kopyala',
    clearConfirmTitle: 'Bu seans temizlensin mi?',
    clearConfirmBody: 'Bu seanstaki tüm tekne atamaları kaldırılır. Kaydedene kadar üyeler etkilenmez.',
    clearConfirm: 'Evet, temizle',
    boatNoteLabel: 'Tekne notu (isteğe bağlı)',
    weatherNote: 'Hava durumu notu',
    weatherNoteHint: 'Ör. "Rüzgâr batıdan 15 km/s, dalga düşük". Üyeler görür.',
    trainingNotesLabel: 'Antrenman notu',
    trainingNotesHint: 'Ör. ısınma, tempo, dönüş noktaları. Üyeler görür.',
    statusDraft: 'Taslak — üyeler görmüyor',
    statusPublished: (version: number) => `Yayında (sürüm ${version})`,
    unsaved: 'Kaydedilmemiş değişiklikler var',
    upToDate: 'Tüm değişiklikler kaydedildi',
    saveDraft: 'Taslağı kaydet',
    publish: 'Yayınla',
    update: 'Güncelle',
    unpublish: 'Yayından kaldır',
    saving: 'Kaydediliyor…',
    draftSaved: 'Taslak kaydedildi.',
    publishedToast: 'Program yayınlandı.',
    updatedToast: 'Program güncellendi.',
    unpublishedToast: 'Program yayından kaldırıldı.',
    unpublishConfirmTitle: 'Program yayından kaldırılsın mı?',
    unpublishConfirmBody: 'Üyeler programı artık göremez. Şu anki düzenlemeleriniz taslak olarak kaydedilir.',
    emptyPublish: 'Yayınlamak için en az bir tekneye ekip atayın.',
    summaryHeading: 'Katılım özeti',
    summaryHint: '"Katılıyorum" diyenler ve hangi seanslarda yer aldıkları.',
    noSessions: 'Hiç seansta yok',
    seasonCount: (n: number) => `${n} seans`,
    noAnswerTag: 'Yanıt yok',
    notAttendingTag: 'Katılmıyor',
    noNotes: 'Not yok',
    // picker
    pickerTitle: (boat: string, range: string) => `${boat} · ${range}`,
    pickerHint: 'Ekibe eklemek veya çıkarmak için dokunun.',
    pickerDone: 'Tamam',
    attendingGroup: 'Katılıyor',
    noAnswerGroup: 'Yanıt vermedi',
    notAttendingGroup: 'Katılmıyor',
    otherMembers: 'Yanıt vermeyenler ve katılmayanlar',
    inOtherBoat: (boat: string) => `Bu seansta ${boat} teknesinde`,
    boatFull: 'Tekne dolu',
    noMembersToPick: 'Seçilebilecek üye yok.',
    // warnings
    warnTitle: 'Yayınlamadan önce',
    warnUnassigned: (names: string) => `${names} hiçbir seansa atanmadı.`,
    warnNotAttending: (names: string) => `${names} "Katılmıyorum" demişti ama programda.`,
    warnNoAnswer: (names: string) => `${names} henüz yanıt vermedi ama programda.`,
    warnQuestion: 'Yine de devam edilsin mi?',
    publishAnyway: 'Yine de yayınla',
    updateAnyway: 'Yine de güncelle',
    backToEditing: 'Düzenlemeye dön',
    // leaving
    leaveTitle: 'Kaydedilmemiş değişiklikler',
    leaveBody: 'Bu sayfadan çıkarsanız yaptığınız değişiklikler kaybolur.',
    leaveStay: 'Kal',
    leaveGo: 'Kaydetmeden çık',
    // states
    needBoats: 'Önce tekne ekleyin',
    needBoatsBody: 'Program hazırlamak için Diğer → Tekneler bölümünden en az bir kullanımdaki tekne olmalı.',
    needBoatsAction: 'Teknelere git',
    readOnly: 'Bu antrenmanın programı artık düzenlenemez.',
    noProgramYet: 'Bu antrenman için program hazırlanmadı.',
    notify: 'Üyelere bildirim gönder',
    notifyHint: 'Yayınlarken programı görecek üyeler; güncellerken yalnızca ekibi değişenler bilgilendirilir.',
  },

  attendance: {
    addSession: 'Seans ekle',
    removeSession: 'Eklenen son seansı kaldır',
    sessionHint: 'Antrenman planlanandan uzun sürdüyse yeni bir seans ekleyin; önceki seanstaki kişiler "Geldi" olarak taşınır, gerekirse düzeltin.',
    title: 'Yoklama',
    notStartedTitle: 'Yoklama henüz alınamaz',
    notStartedBody: (time: string) => `Yoklama antrenman başladıktan sonra alınabilir (${time}).`,
    cancelledBody: 'İptal edilen antrenmanın yoklaması alınmaz.',
    present: 'Geldi',
    absent: 'Gelmedi',
    markGroup: (name: string) => `${name} için durum`,
    walkIn: 'Ek kişi',
    addPerson: 'Kişi ekle',
    removeWalkIn: (name: string) => `${name} listeden çıkar`,
    emptySlot: 'Bu seans için kimse listelenmedi. "Kişi ekle" ile ekleyin.',
    planFromProgram: 'Liste, programdaki tekne ekiplerinden hazırlandı. Gelmeyenleri "Gelmedi" yapın, ekstra gelenleri ekleyin.',
    planFromRsvp: 'Programda ekip yok; "Katılıyorum" diyenler listelendi. Gelmeyenleri "Gelmedi" yapın, ekstra gelenleri ekleyin.',
    summary: (people: number, sessions: number) => `${people} kişi · ${sessions} seans geldi`,
    summaryAbsent: (n: number) => `${n} kişi gelmedi`,
    save: 'Kaydet',
    saving: 'Kaydediliyor…',
    complete: 'Yoklamayı tamamla',
    update: 'Güncelle',
    savedToast: 'Yoklama kaydedildi.',
    completedToast: 'Yoklama tamamlandı.',
    updatedToast: 'Yoklama güncellendi.',
    completeConfirmTitle: 'Yoklama tamamlansın mı?',
    completeConfirmBody: 'Antrenman "Tamamlandı" olur ve gelenler aylık istatistiğe işlenir. Sonradan düzeltebilirsiniz.',
    completeConfirm: 'Evet, tamamla',
    statusCompleted: 'Tamamlandı — istatistiklere işlendi',
    statusInProgress: 'Henüz istatistiklere işlenmedi',
    unsaved: 'Kaydedilmemiş değişiklikler var',
    upToDate: 'Tüm değişiklikler kaydedildi',
    nothingToComplete: 'Tamamlamak için en az bir kişi listelenmeli.',
    pickerTitle: (range: string) => `Kişi ekle · ${range}`,
    pickerHint: 'Gelen ama listede olmayan üyeye dokunun.',
    pickerNone: 'Eklenebilecek üye kalmadı.',
    pickerDone: 'Tamam',
    pickerSearch: 'İsim ara',
    loadError: 'Yoklama yüklenemedi.',
    // member
    mine: 'Yoklamanız',
    mineNone: 'Bu antrenmanda yoklama kaydınız yok.',
    minePresent: 'Katıldınız',
    mineAbsent: 'Gelmediniz',
    badgeAttended: (n: number) => `${n} seans katıldınız`,
    badgeNone: 'Katılmadınız',
    badgePending: 'Yoklama bekleniyor',
    // coach lists
    badgeCounts: (people: number, sessions: number) => `${people} kişi · ${sessions} seans`,
    badgeMissing: 'Yoklama alınmadı',
    needsHeading: 'Yoklaması bekleyenler',
    needsAction: 'Yoklama al',
  },

  stats: {
    title: 'İstatistik',
    prevMonth: 'Önceki ay',
    nextMonth: 'Sonraki ay',
    monthNav: 'Ay seçimi',
    mine: 'Ayınız',
    sessions: 'seans',
    trainingDays: 'antrenman günü',
    leaderboard: 'Aylık sıralama',
    leaderboardHint: 'Sıralama, o ay yoklamada "Geldi" işaretlenen seans sayısına göre yapılır ve her ay sıfırdan başlar.',
    leaderboardEmptyTitle: 'Bu ay için henüz kayıt yok',
    leaderboardEmptyBody: 'Antrenmanların yoklaması tamamlandıkça sıralama burada görünür.',
    tied: 'eşit',
    noRank: 'henüz sıralamada değil',
    nobodyYet: 'Bu ay henüz kimse kürek çekmedi. Tüm üyeler 0 seansla listelenir; ilk seansı siz alın!',
    you: 'Siz',
    sessionsLabel: (n: number) => `${n} seans`,
    daysLabel: (n: number) => `${n} gün`,
    loadError: 'İstatistikler yüklenemedi.',
    // coach
    coachSummary: (members: number, sessions: number) => `${members} üye · toplam ${sessions} seans`,
    membersHeading: 'Üyeler',
    noMembers: 'Henüz üye yok.',
    exportHeading: 'Dışa aktar',
    exportSummary: 'Özet (CSV)',
    exportDetail: 'Ayrıntılı (CSV)',
    exportNote: 'Excel\'de açılacak şekilde noktalı virgülle ayrılmış dosya hazırlanır.',
    exported: 'Dosya hazırlandı.',
    exportError: 'Dosya hazırlanamadı.',
    exportEmpty: 'Bu ay için dışa aktarılacak kayıt yok.',
    memberBack: 'İstatistik',
    memberHistory: 'Katıldığı antrenmanlar',
    memberHistoryNone: 'Bu ay kayıt yok.',
    memberNotFound: 'Üye bulunamadı',
    hoursPresent: 'Geldi',
    hoursAbsent: 'Gelmedi',
  },

  weather: {
    heading: 'Hava durumu',
    notLoaded: 'Hava durumu henüz alınmadı.',
    tooFar: 'Hava tahmini, antrenmana en fazla 16 gün kala görünür.',
    forecastAt: (time: string) => `Tahmin: ${time}`,
    forSession: (range: string) => `Hava durumu, ${range}`,
    mySessionLater: 'Bu seansın hava tahmini, antrenmana yaklaştıkça burada görünür.',
    attribution: 'Hava verisi',
    marineNote: 'Dalga değerleri açık deniz modelinden gelir; kıyıda yaklaşık olabilir.',
    refresh: 'Yenile',
    refreshing: 'Yenileniyor…',
    refreshed: 'Hava durumu güncellendi.',
    refreshError: 'Hava durumu güncellenemedi.',
    gust: (n: string) => `hamle ${n} km/s`,
    wave: (n: string) => `dalga ${n} m`,
    rain: (percent: string) => `yağış %${percent}`,
    beaufort: (n: number) => `Bofor ${n}`,
    advisoryTitle: 'Dikkat: uyarı eşiği aşıldı',
    advisoryGust: (value: string, threshold: string) => `Rüzgâr hamlesi ${value} km/s (eşik ${threshold})`,
    advisoryWave: (value: string, threshold: string) => `Dalga ${value} m (eşik ${threshold})`,
    advisoryHint: 'Karar antrenöre aittir; uygulama hiçbir antrenmanı kendiliğinden iptal etmez.',
    unknown: 'Bilinmiyor',
  },

  a11y: {
    skipToContent: 'Ana içeriğe geç',
  },

  audit: {
    title: 'Değişiklik geçmişi',
    hint: 'Antrenörlerin yaptığı değişiklikler. Yalnızca antrenörler görebilir; kayıtlar bir yıl saklanır.',
    back: 'Diğer',
    filterLabel: 'Kayıt türü',
    filters: { all: 'Tümü', training: 'Antrenman', program: 'Program', attendance: 'Yoklama', member: 'Üyeler', settings: 'Ayarlar' },
    emptyTitle: 'Henüz kayıt yok',
    emptyBody: 'Antrenörler bir şey değiştirdiğinde burada görünür.',
    loadError: 'Değişiklik geçmişi yüklenemedi.',
    more: 'Daha eski kayıtlar',
    by: (name: string) => `${name} tarafından`,
    system: 'Sistem',
    changed: (fields: string) => `Değişen: ${fields}`,
    records: (n: number) => `${n} kayıt`,
    fields: {
      title: 'başlık',
      starts_at: 'başlangıç zamanı',
      rsvp_deadline: 'son yanıt zamanı',
      notes: 'notlar',
      name: 'ad',
      capacity: 'kapasite',
      is_active: 'kullanım durumu',
      requires_full_crew: 'tam kadro kuralı',
      default_rsvp_lead_hours: 'varsayılan yanıt süresi',
      reminder_lead_hours: 'hatırlatma zamanı',
      wind_gust_warn_kmh: 'rüzgâr hamlesi eşiği',
      wave_warn_m: 'dalga eşiği',
      full_name: 'ad soyad',
      phone: 'telefon',
    },
  },

  notifications: {
    title: 'Bildirimler',
    markAll: 'Tümünü okundu yap',
    emptyTitle: 'Henüz bildirim yok',
    emptyBody: 'Antrenman ve program haberleri burada görünür.',
    loadError: 'Bildirimler yüklenemedi.',
    bellLabel: (unread: number) => (unread === 0 ? 'Bildirimler' : `Bildirimler, ${unread} okunmamış`),
    justNow: 'az önce',
    minutesAgo: (n: number) => `${n} dk önce`,
    hoursAgo: (n: number) => `${n} sa önce`,
    yesterday: (time: string) => `Dün ${time}`,
    unreadMark: 'Okunmadı',
    inboxLink: 'Bildirim kutusu',
  },

  settings: {
    title: 'Kulüp ayarları',
    back: 'Diğer',
    rsvpLead: 'Varsayılan yanıt süresi (saat)',
    rsvpLeadHint: 'Yeni antrenmanda "son yanıt zamanı" başlangıçtan bu kadar saat önceye ayarlanır (12, 24 veya 48 seçenek olarak hazır gelir).',
    reminderLead: 'Hatırlatma zamanı (saat)',
    reminderLeadHint: 'Yanıt vermeyen üyelere, son yanıt zamanından bu kadar saat önce hatırlatma gönderilir.',
    gust: 'Rüzgâr hamlesi uyarı eşiği (km/s)',
    wave: 'Dalga yüksekliği uyarı eşiği (m)',
    thresholdHint: 'İsteğe bağlı. Aşılırsa yalnızca antrenörlere uyarı gösterilir; hiçbir şey kendiliğinden iptal edilmez.',
    thresholdEmpty: 'Boş bırakırsanız uyarı verilmez.',
    site: 'Antrenman yeri',
    siteHint: 'Hava tahmini bu konum için alınır.',
    saved: 'Ayarlar kaydedildi.',
    save: 'Kaydet',
    saving: 'Kaydediliyor…',
    loadError: 'Ayarlar yüklenemedi.',
    invalidHours: 'Geçerli bir sayı girin.',
    rsvpRange: '0 ile 168 arasında olmalı.',
    reminderRange: '1 ile 24 arasında olmalı.',
    gustRange: '1 ile 200 arasında olmalı.',
    waveRange: '0,1 ile 10 arasında olmalı.',
  },

  boats: {
    title: 'Tekneler',
    add: 'Tekne ekle',
    newTitle: 'Yeni tekne',
    editTitle: 'Tekneyi düzenle',
    name: 'Tekne adı',
    nameRequired: 'Tekne adı 1–40 karakter olmalı.',
    capacity: 'Kişi kapasitesi',
    capacityOption: (n: number) => `${n} kişilik`,
    active: 'Kullanımda',
    inactive: 'Kullanım dışı',
    activeLabel: 'Tekne kullanımda',
    activeHint: 'Kullanım dışı tekneler antrenman programında seçilemez.',
    fullCrewLabel: 'Tam kadro zorunlu',
    fullCrewHint: 'Bu tekne her seansta tam kapasiteyle kullanılmalı (ör. C4X: tam 4 kişi). Eksik veya fazla kişiyle program yayınlanamaz.',
    fullCrewBadge: 'Tam kadro',
    duplicate: 'Bu isimde bir tekne zaten var.',
    saved: 'Tekne kaydedildi.',
    save: 'Kaydet',
    saving: 'Kaydediliyor…',
    emptyTitle: 'Henüz tekne yok',
    emptyBody: 'Program hazırlayabilmek için en az bir tekne ekleyin.',
    loadError: 'Tekneler yüklenemedi.',
    back: 'Diğer',
  },

  contact: {
    title: 'Kişi bilgisi',
    phone: 'Telefon',
    call: 'Ara',
    noPhone: 'Bu üye için telefon numarası eklenmemiş.',
    close: 'Kapat',
    directoryTitle: 'Kulüp üyeleri',
    directoryHint: 'Kulüp üyelerinin adı ve telefon numarası. Yalnızca kulüp üyeleri ve antrenörler görebilir.',
    searchLabel: 'Üye ara',
    searchPlaceholder: 'İsim ara',
    noResults: 'Aramanızla eşleşen üye yok.',
    emptyTitle: 'Henüz üye yok',
    emptyBody: 'Kulüp üyeleri burada listelenir.',
    loadError: 'Üye listesi yüklenemedi.',
    callLabel: (name: string) => `${name} kişisini ara`,
    back: 'Profil',
    openProfile: 'Profili aç',
    openProfileLabel: (name: string) => `${name} profilini aç`,
  },

  person: {
    back: 'Kulüp üyeleri',
    notFound: 'Bu üye bulunamadı.',
    notFoundBody: 'Üye listesinde değil ya da artık kulüpte değil.',
    loadError: 'Üye bilgisi yüklenemedi.',
    historyHeading: 'Birlikte kürek çektiğiniz seanslar',
    historyHint: 'Yalnızca ikinizin de aynı teknede olup yoklamada "Geldi" işaretlendiği seanslar sayılır.',
    summary: (sessions: number, days: number) => `${sessions} seans · ${days} antrenman günü`,
    boatCount: (name: string, count: number) => `${name}: ${count}`,
    emptyTitle: 'Henüz birlikte kürek çekmediniz',
    emptyBody: 'Aynı teknede yer aldığınız ve yoklaması tamamlanan seanslar burada görünür.',
    capped: (n: number) => `En son ${n} seans gösteriliyor.`,
    loadHistoryError: 'Birlikte kürek çekme geçmişi yüklenemedi.',
  },

  notFound: {
    title: 'Sayfa bulunamadı',
    body: 'Aradığınız sayfa yok veya taşınmış olabilir.',
    home: 'Ana sayfaya dön',
  },
} as const;
